global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "cloudflare"

log:
  filePath: "/var/log/traefik/traefik.log"
  level: "DEBUG"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 200

api:
  dashboard: true
  insecure: false

providers:
  swarm:
    endpoint: unix:///var/run/docker.sock
    network: "traefik_proxy"
    exposedbydefault: false
  file:
    watch: true
    directory: "/dynamic/"

certificatesResolvers:
  cloudflare:
    acme:
      email: 'dylan.mgroff@gmail.com'
      storage: '/letsencrypt/acme.json'
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      dnsChallenge:
        provider: 'cloudflare'
        delayBeforeCheck: '0'
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
          - '8.8.8.8:53'